HOSTS:
  master:
    roles:
      - master
      - database
      - dashboard
    platform: el-7-x86_64
    hypervisor: vagrant
    vagrant_memsize: 6144
    vagrant_cpus: 4
    box: puppetlabs/centos-7.0-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
  agent:
    roles:
      - agent
      - frictionless
    platform: el-7-x86_64
    frictionless_options:
      extension_requests:
        pp_role: linux_webserver
      main:
        certname: testagent
    hypervisor: vagrant
    box: puppetlabs/centos-7.0-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
CONFIG:
  nfs_server: none
  consoleport: 443
  pe_dir: http://enterprise.delivery.puppetlabs.net/2017.2/ci-ready/
  log_level: debug
  preserve_host: never
